FROM tomcat:8.0.46-jre8

ENV MYSQL_FHIR_USER fhirjpa
ENV MYSQL_FHIR_PASSWORD fhirjpa

# Install MySql Client to ensure that MySql server is initialised before starting Tomcat server
RUN apt-get update
RUN apt-get install -y mysql-client

RUN rm -rf /usr/local/tomcat/webapps/*;

RUN  mkdir /usr/local/tomcat/webapps/ROOT;

ADD index.jsp /usr/local/tomcat/webapps/ROOT/index.jsp
ADD logging.properties /usr/local/tomcat/conf/logging.properties
ADD server.xml /usr/local/tomcat/conf/server.xml
# ADD hawtio.war /usr/local/tomcat/webapps/
ADD target/careconnect-ri.war /usr/local/tomcat/webapps/

ADD start-server.sh /start-server.sh
RUN chmod 777 /start-server.sh


RUN echo "Database Username: ${MYSQL_FHIR_USER}"
RUN echo "Database Password: ${MYSQL_FHIR_PASSWORD}"

# See CareConnectAPI for details on pulling and running docker images https://care-connect-api.netlify.com/ccri_docker.html

#CMD ["catalina.sh", "run"]
CMD /start-server.sh ${MYSQL_FHIR_USER} ${MYSQL_FHIR_PASSWORD}